#pragma once

// Shared constants for TurboQuant 3-bit (tbq3_0).
// Included by both the CPU backend (ggml-quants.c) and CUDA backend (cpy-utils.cuh)
// so there is a single source of truth for the codebook and sign pattern.
// Do not add ggml headers here — this file is included by CUDA device code.

// 3-bit Lloyd-Max centroids for N(0,1), 8 levels, sorted ascending.
#define TBQ3_CODEBOOK_INIT \
    { -2.1520f, -1.3439f, -0.7560f, -0.2451f, \
       0.2451f,  0.7560f,  1.3439f,  2.1520f }

// Random sign flips for the randomized Hadamard transform.
// Generated by xorshift32 with seed 42: sign = (state >> 31) ? 1 : -1.
#define TBQ3_SIGNS_INIT \
    { -1,  1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1, \
      -1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1, -1, -1, \
       1, -1,  1,  1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1, \
      -1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1, \
      -1,  1, -1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, \
      -1, -1,  1,  1, -1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1, -1, \
      -1, -1,  1,  1,  1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1, \
       1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1 }
